DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS baseball_teams;
DROP TABLE IF EXISTS baseball_playoffs;

CREATE TABLE cities (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  city TEXT NOT NULL
);

CREATE TABLE baseball_teams (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  team TEXT NOT NULL,
  cityId INTEGER REFERENCES cities(id)
);

CREATE TABLE baseball_playoffs (
  id INTEGER PRIMARY KEY REFERENCES baseball_teams(id),
--   vs NL EAST TEAMS
  wins_atl INTEGER,
  losses_atl INTEGER,
  wins_mia INTEGER,
  losses_mia INTEGER,
  wins_nym INTEGER,
  losses_nym INTEGER,
  wins_phi INTEGER,
  losses_phi INTEGER,
  wins_wsh INTEGER,
  losses_wsh INTEGER,
--   vs NL CENTRAL TEAMS
  wins_chc INTEGER,
  losses_chc INTEGER,
  wins_cin INTEGER,
  losses_cin INTEGER,
  wins_mil INTEGER,
  losses_mil INTEGER,
  wins_pit INTEGER,
  losses_pit INTEGER,
  wins_stl INTEGER,
  losses_stl INTEGER,
--   vs NL WEST TEAMS
  wins_ari INTEGER,
  losses_ari INTEGER,
  wins_col INTEGER,
  losses_col INTEGER,
  wins_lad INTEGER,
  losses_lad INTEGER,
  wins_sd INTEGER,
  losses_sd INTEGER,
  wins_sf INTEGER,
  losses_sf INTEGER,
--   vs AL EAST TEAMS
  wins_bal INTEGER,
  losses_bal INTEGER,
  wins_bos INTEGER,
  losses_bos INTEGER,
  wins_nyy INTEGER,
  losses_nyy INTEGER,
  wins_tb INTEGER,
  losses_tb INTEGER,
  wins_tor INTEGER,
  losses_tor INTEGER,
--   vs AL CENTRAL TEAMS
  wins_cle INTEGER,
  losses_cle INTEGER,
  wins_cws INTEGER,
  losses_cws INTEGER,
  wins_det INTEGER,
  losses_det INTEGER,
  wins_min INTEGER,
  losses_min INTEGER,
  wins_kc INTEGER,
  losses_kc INTEGER,
--   vs AL WEST TEAMS
  wins_hou INTEGER,
  losses_hou INTEGER,
  wins_laa INTEGER,
  losses_laa INTEGER,
  wins_oak INTEGER,
  losses_oak INTEGER,
  wins_sea INTEGER,
  losses_sea INTEGER,
  wins_tex INTEGER,
  losses_tex INTEGER
);